# Generated by Django 5.1.7 on 2025-03-17 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_date_alter_contact_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='name1',
        ),
    ]
