# Generated by Django 5.1.7 on 2025-04-05 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_booking_passengers_and_more'),
    ]

    operations = [
    ]
