# Generated by Django 5.1.7 on 2025-04-05 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_airline_logo_alter_airport_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
    ]
