# Generated by Django 5.1.7 on 2025-04-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_booking_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_passengers',
            field=models.PositiveIntegerField(default=11),
            preserve_default=False,
        ),
    ]
