# Generated by Django 5.1.7 on 2025-04-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_booking_num_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='num_passengers',
        ),
    ]
