# Generated by Django 5.1.7 on 2025-04-05 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_passenger_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='nums_passengers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='home.booking'),
        ),
    ]
