# Generated by Django 5.1.7 on 2025-04-08 13:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_booking_nums_passengers_alter_passenger_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='nums_passengers',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
