# Generated by Django 5.2.13 on 2026-04-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='Credit Card', max_length=50),
        ),
    ]
