# Generated by Django 5.1.7 on 2026-04-29 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_passenger_age_passenger_gender_passenger_is_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.flight'),
        ),
        migrations.CreateModel(
            name='BookingSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('layover_duration', models.DurationField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_segments', to='home.booking')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.flight')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='flights',
            field=models.ManyToManyField(related_name='multi_segment_bookings', through='home.BookingSegment', to='home.flight'),
        ),
    ]
