# Generated by Django 5.1.7 on 2026-04-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_booking_flight_bookingsegment_booking_flights'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='stops',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
