# Generated by Django 5.1.7 on 2026-04-29 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_flightroute_routestop_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='departure_airline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.airline'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='flight_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
