# Generated by Django 5.1.7 on 2026-04-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_routestop_departure_airline_routestop_flight_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightroute',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='flightroute',
            name='flight_number',
        ),
        migrations.AddField(
            model_name='flightroute',
            name='name',
            field=models.CharField(default='New Route', max_length=100),
            preserve_default=False,
        ),
    ]
