# Generated by Django 5.1.7 on 2026-04-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_flight_baggage_allowance_flight_cabin_allowance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='baggage_allowance',
            field=models.CharField(default='Standard baggage included', max_length=80, verbose_name='Baggage'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='cabin_allowance',
            field=models.CharField(default='7 kg cabin bag', max_length=80, verbose_name='Cabin'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='check_in_allowance',
            field=models.CharField(default='15 kg check-in bag', max_length=80, verbose_name='Check In'),
        ),
    ]
