# Generated by Django 5.1.7 on 2026-04-30 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_flight_baggage_allowance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='baggage_allowance',
        ),
    ]
