# Generated by Django 5.1.7 on 2026-04-30 18:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_add_booking_fare_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='fare_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('STUDENT', 'Student')], default='NORMAL', max_length=10),
        ),
    ]
